version: '3'

services:

  # proxy use for routing between FE, BE, WS, ...
  ecm-proxy:
    container_name: "proxy"
    hostname: "proxy"
    image: nginx
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/config.nginx
    ports:
      - "80:80"
    command: > 
      /bin/bash -c "envsubst 
      < /etc/nginx/conf.d/config.nginx
      > /etc/nginx/conf.d/default.conf
      && exec nginx -g 'daemon off;'"

  # React application
  ecm-web:
    container_name: "ecm-web"
    hostname: "ecm-web"
    build:
      context: .
      dockerfile: ./Dockerfile-local
    volumes:
      - "./:/app"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "81:3000"

