version: '3'

services:

  ecm-gateway:
    container_name: "ecm-gateway"
    hostname: "ecm-gateway"
    image: nginx
    volumes:
    # - ./proxy/letencrypt/certs:/etc/ssl/certs
      - ./gateway/nginx.conf:/etc/nginx/conf.d/config.nginx
    ports:
      - "30001:80"
    command: > 
      /bin/bash -c "envsubst 
      < /etc/nginx/conf.d/config.nginx
      > /etc/nginx/conf.d/default.conf
      && exec nginx -g 'daemon off;'"
    networks:
      - ecm

  ecm-system:
    container_name: "ecm-system"
    hostname: "ecm-system"
    build:
      context: ./system
      dockerfile: Dockerfile.dev
    expose:
      - 5000
    # ports:
    #   - '5000:5000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - KAFKA_BROKER_1=${KAFKA_BROKER_1}
    volumes:
      - ./system/:/app
    depends_on:
      - ecm-gateway
    deploy:
      replicas: 1
    networks:
      - ecm
  
networks:
  ecm:
    driver: bridge
