version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    expose:
      - 2181
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    # volumes: 
      # - ./volumes/zoo/data:/var/lib/zookeeper/data
      # - ./volumes/zoo/log:/var/lib/zookeeper/log
    networks:
      - ecm
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  broker:
    image: confluentinc/cp-server:7.3.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    expose:
      - 9092
      - 9191
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    # volumes:
      # - ./volumes/kafka-broker/data:/var/lib/kafka/data
    networks:
      - ecm
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

  ecm-gateway:
    container_name: "ecm-gateway"
    hostname: "ecm-gateway"
    image: nginx
    volumes:
    # - ./proxy/letencrypt/certs:/etc/ssl/certs
      - ./gateway/nginx.conf:/etc/nginx/conf.d/config.nginx
    ports:
      - "30001:80"
    command: > 
      /bin/bash -c "envsubst 
      < /etc/nginx/conf.d/config.nginx
      > /etc/nginx/conf.d/default.conf
      && exec nginx -g 'daemon off;'"
    networks:
      - ecm

  ecm-system:
    container_name: "ecm-system"
    hostname: "ecm-system"
    build:
      context: ./system
      dockerfile: Dockerfile.dev
    expose:
      - 5000
    # ports:
    #   - '5000:5000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - KAFKA_BROKER_1=${KAFKA_BROKER_1}
    volumes:
      - ./system/:/app
    depends_on:
      - zookeeper
      - broker
    deploy:
      replicas: 1
    networks:
      - ecm
  
networks:
  ecm:
    driver: bridge
